# Generated by Django 5.0.1 on 2024-01-22 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xuexiaoinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuexiaomingcheng', models.CharField(max_length=200, verbose_name='学校名称')),
                ('xuexiaobiaoshima', models.IntegerField(default=4111010001, verbose_name='学校标识码')),
                ('zhuguanbumen', models.CharField(max_length=200, verbose_name='主管部门')),
                ('suozaidi', models.CharField(max_length=200, verbose_name='所在地')),
                ('bianxuecengci', models.CharField(choices=[('本科', '本科'), ('专科', '专科')], max_length=200, verbose_name='办学层次')),
            ],
            options={
                'verbose_name': '学校信息',
                'verbose_name_plural': '学校信息',
            },
        ),
        migrations.CreateModel(
            name='zhaoshengxinxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhuanyemingcheng', models.CharField(max_length=200, verbose_name='专业名称')),
                ('zhaoshengjihua', models.IntegerField(verbose_name='招生计划')),
                ('xuefei', models.FloatField(verbose_name='学费')),
                ('zhaoshengleixing', models.CharField(max_length=200, verbose_name='招生类型')),
                ('xingzhi', models.CharField(default='专科', max_length=200, verbose_name='性质（专科/本科）')),
                ('nianfen', models.IntegerField(default=2024, verbose_name='年份')),
                ('zhuanyeleibie', models.CharField(max_length=200, verbose_name='专业类别')),
                ('kebaozhiyuansl', models.IntegerField(verbose_name='可报志愿数量')),
                ('kaoshineirong', models.TextField(verbose_name='考试内容')),
                ('xuexiaomingcheng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.xuexiaoinfo')),
            ],
            options={
                'verbose_name': '招生信息',
                'verbose_name_plural': '招生信息',
            },
        ),
    ]
