# Generated by Django 5.0.1 on 2024-01-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhaoshengxinxi',
            name='xingzhi',
            field=models.CharField(choices=[('本科', '本科'), ('专科', '专科')], max_length=200, verbose_name='性质（专科/本科）'),
        ),
    ]
