# Generated by Django 5.0.1 on 2024-01-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_alter_zhaoshengxinxi_xuexiaomingcheng'),
    ]

    operations = [
        migrations.AddField(
            model_name='xuexiaoinfo',
            name='beizhu',
            field=models.CharField(default='', max_length=200, verbose_name='备注'),
        ),
    ]
