# Generated by Django 5.0.1 on 2024-01-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_xuexiaoinfo_beizhu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xuexiaoinfo',
            name='beizhu',
            field=models.CharField(choices=[('公办', '公办'), ('民办', '民办'), ('中外合作办学', '中外合作办学'), ('内地与港澳台地区合作办学', '内地与港澳台地区合作办学')], max_length=200, verbose_name='备注'),
        ),
    ]
