# Generated by Django 5.0.1 on 2024-01-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_alter_xuexiaoinfo_beizhu'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhaoshengxinxi',
            name='kaoshifangshi',
            field=models.CharField(choices=[('线上', '线上'), ('线下', '线下')], default='线下', max_length=200, verbose_name='考试方式'),
        ),
    ]
