# Generated by Django 5.0.1 on 2024-01-26 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_zhaoshengxinxi_kaoshifangshi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xuexiaoinfo',
            name='beizhu',
            field=models.CharField(blank=True, choices=[('公办', '公办'), ('民办', '民办'), ('中外合作办学', '中外合作办学'), ('内地与港澳台地区合作办学', '内地与港澳台地区合作办学')], max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='xuexiaoinfo',
            name='bianxuecengci',
            field=models.CharField(blank=True, choices=[('本科', '本科'), ('专科', '专科')], max_length=200, null=True, verbose_name='办学层次'),
        ),
        migrations.AlterField(
            model_name='xuexiaoinfo',
            name='suozaidi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='xuexiaoinfo',
            name='xuexiaobiaoshima',
            field=models.IntegerField(blank=True, default=4111010001, null=True, verbose_name='学校标识码'),
        ),
        migrations.AlterField(
            model_name='xuexiaoinfo',
            name='zhuguanbumen',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='主管部门'),
        ),
        migrations.AlterField(
            model_name='zhaoshengxinxi',
            name='kaoshifangshi',
            field=models.CharField(blank=True, choices=[('线上', '线上'), ('线下', '线下')], default='线下', max_length=200, null=True, verbose_name='考试方式'),
        ),
        migrations.AlterField(
            model_name='zhaoshengxinxi',
            name='kaoshineirong',
            field=models.TextField(blank=True, null=True, verbose_name='考试内容'),
        ),
        migrations.AlterField(
            model_name='zhaoshengxinxi',
            name='kebaozhiyuansl',
            field=models.IntegerField(blank=True, null=True, verbose_name='可报志愿数量'),
        ),
        migrations.AlterField(
            model_name='zhaoshengxinxi',
            name='nianfen',
            field=models.IntegerField(blank=True, default=2024, null=True, verbose_name='年份'),
        ),
        migrations.AlterField(
            model_name='zhaoshengxinxi',
            name='xingzhi',
            field=models.CharField(blank=True, choices=[('本科', '本科'), ('专科', '专科')], max_length=200, null=True, verbose_name='性质（专科/本科）'),
        ),
        migrations.AlterField(
            model_name='zhaoshengxinxi',
            name='xuefei',
            field=models.FloatField(blank=True, null=True, verbose_name='学费'),
        ),
        migrations.AlterField(
            model_name='zhaoshengxinxi',
            name='xuexiaomingcheng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='query.xuexiaoinfo', verbose_name='学校名称'),
        ),
        migrations.AlterField(
            model_name='zhaoshengxinxi',
            name='zhaoshengjihua',
            field=models.IntegerField(blank=True, null=True, verbose_name='招生计划'),
        ),
        migrations.AlterField(
            model_name='zhaoshengxinxi',
            name='zhaoshengleixing',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='招生类型'),
        ),
        migrations.AlterField(
            model_name='zhaoshengxinxi',
            name='zhuanyeleibie',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='专业类别'),
        ),
        migrations.AlterField(
            model_name='zhaoshengxinxi',
            name='zhuanyemingcheng',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='专业名称'),
        ),
    ]
