# Generated by Django 5.0.1 on 2024-01-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0007_alter_xuexiaoinfo_beizhu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xuexiaoinfo',
            old_name='bianxuecengci',
            new_name='banxuecengci',
        ),
    ]
