# Generated by Django 5.0.1 on 2024-01-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0008_rename_bianxuecengci_xuexiaoinfo_banxuecengci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xuexiaoinfo',
            name='beizhu',
            field=models.CharField(blank=True, choices=[('公办', '公办'), ('民办', '民办'), ('中外合作办学', '中外合作办学'), ('内地与港澳台地区合作办学', '内地与港澳台地区合作办学')], default='公办', max_length=200, null=True, verbose_name='备注'),
        ),
    ]
