# Generated by Django 5.0.1 on 2024-01-27 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0010_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 17, 11, 33, 918954), verbose_name='设置时间'),
        ),
    ]
