# Generated by Django 5.0.1 on 2024-01-28 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0011_alter_days_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imgs/admin/')),
                ('is_logo', models.BooleanField(default=False)),
                ('is_watermark', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '图片功能',
                'verbose_name_plural': '图片功能',
            },
        ),
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 28, 8, 22, 2, 358898), verbose_name='设置时间'),
        ),
    ]
