# Generated by Django 5.0.1 on 2024-01-28 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0013_alter_days_day_alter_images_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 28, 9, 15, 23, 861120), verbose_name='设置时间'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='static/imgs/admin/', verbose_name='路径'),
        ),
    ]
