# Generated by Django 5.0.1 on 2024-01-29 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0014_alter_days_day_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 8, 54, 13, 619977), verbose_name='设置时间'),
        ),
    ]
