# Generated by Django 5.0.1 on 2024-01-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0017_alter_days_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='media/imgs/admin/', verbose_name='路径'),
        ),
        migrations.AlterField(
            model_name='xuexiaoinfo',
            name='xuexiaobiaoshima',
            field=models.TextField(blank=True, default=4111010001, null=True, verbose_name='学校标识码'),
        ),
    ]
