# Generated by Django 5.0.1 on 2024-01-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0018_alter_images_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xuexiaoinfo',
            name='xuexiaobiaoshima',
            field=models.TextField(blank=True, default='4111010001', null=True, verbose_name='学校标识码'),
        ),
    ]
