# Generated by Django 5.0.1 on 2024-01-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0019_alter_xuexiaoinfo_xuexiaobiaoshima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='imgs/admin/', verbose_name='路径'),
        ),
    ]
