# Generated by Django 5.0.1 on 2024-02-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0020_alter_images_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='zhaoshengxinxi',
            new_name='zhaoshengxinxi_danzhao',
        ),
        migrations.AlterModelOptions(
            name='zhaoshengxinxi_danzhao',
            options={'verbose_name': '招生信息-单招', 'verbose_name_plural': '招生信息-单招'},
        ),
    ]
