# Generated by Django 5.0.1 on 2024-02-06 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0021_rename_zhaoshengxinxi_zhaoshengxinxi_danzhao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhaoshengxinxi_danzhao',
            name='xuexiaomingcheng',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.xuexiaoinfo', verbose_name='学校名称'),
        ),
        migrations.CreateModel(
            name='fenshuxianchaxun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhuanyeleibie', models.CharField(max_length=200, verbose_name='专业类别')),
                ('zhaoshengzhuanye', models.CharField(max_length=200, verbose_name='招生专业')),
                ('zuidifenshu', models.IntegerField(verbose_name='最低分数')),
                ('zuidiweici', models.IntegerField(verbose_name='最低位次')),
                ('benkezigexian', models.IntegerField(null=True, verbose_name='本科资格线')),
                ('zhuankezigexian', models.IntegerField(null=True, verbose_name='专科资格线')),
                ('nianfen', models.DateTimeField(default=2024, verbose_name='年份')),
                ('xuexiaomingcheng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.xuexiaoinfo', verbose_name='学校名称')),
            ],
            options={
                'verbose_name': '分数线查询',
                'verbose_name_plural': '分数线查询',
            },
        ),
    ]
