# Generated by Django 5.0.1 on 2024-02-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0022_alter_zhaoshengxinxi_danzhao_xuexiaomingcheng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fenshuxianchaxun',
            name='nianfen',
            field=models.IntegerField(default=2024, verbose_name='年份'),
        ),
    ]
