# Generated by Django 5.0.1 on 2024-02-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0023_alter_fenshuxianchaxun_nianfen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fenshuxianchaxun',
            name='benkezigexian',
            field=models.IntegerField(blank=True, null=True, verbose_name='本科资格线'),
        ),
        migrations.AlterField(
            model_name='fenshuxianchaxun',
            name='zhuankezigexian',
            field=models.IntegerField(blank=True, null=True, verbose_name='专科资格线'),
        ),
    ]
