# Generated by Django 5.0.1 on 2024-02-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0026_alter_listgroupitem_options_listgroupitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
